name: Context LBG

env:
 MY_VAR: "workflow"
on:
 workflow_dispatch:
jobs:
 context:
  runs-on: ubuntu-latest
  env:
   MY_VAR: "jobs"
  steps: 
  - name: Context
    env:
     MY_VAR: "steps"
    run: |
     echo "Author name ${{github.actor}}"
     echo "Event is ${{github.event_name}}"
     echo "ref value ${{github.ref}}"
     echo "Commit SHA value ${{github.SHA}}"
     echo "Run id value ${{github.run_id}}"
     echo "Run number is ${{github.run_number}}"
     echo "ENV value ${{env.MY_VAR}}"
  - name: Env
    run: echo "ENV value ${{vars.MY_VAR}}" 
     
     
 
