name: Environment LBG


on:
 workflow_dispatch:
  inputs:
   TAR_ENVIRONMENT:
    type: environment
    default: dev
    
jobs:
 environment-ci:
  runs-on: ubuntu-latest
  environment: ${{inputs.TAR_ENVIRONMENT}}
  steps:
   - name: Print
     run: echo "Environment is ${{vars.USER}}"
