name: First Workflow - demo

on:
  workflow_dispatch
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - name: Print
      run: echo "Build"
  
  
 test:
  needs: build
  runs-on:  ubuntu-latest
  steps:
    - name: Print
      run: echo "test"

 staging:
   needs: [ build, test]
   runs-on:  ubuntu-latest
   steps:
    - name: Print
      run: echo "staging"
 
 deploy:
   needs: [ build, test, staging]
   runs-on:  ubuntu-latest
   steps:
    - name: Print
      run: echo "deploy"
